# Generated by Django 3.1.2 on 2020-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
