# Generated by Django 3.1.2 on 2020-11-21 10:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201120_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
