# Generated by Django 3.1.2 on 2020-11-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food', models.CharField(max_length=254)),
                ('Grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Calories', models.IntegerField()),
                ('Protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Saturated_Fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.category')),
            ],
        ),
    ]
