# Generated by Django 3.1.2 on 2020-11-13 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={'verbose_name_plural': 'Nutrition'},
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='Calories',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
