# Generated by Django 3.1.2 on 2020-11-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
