# Generated by Django 3.1.2 on 2020-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='length',
            field=models.TimeField(),
        ),
    ]
