# Generated by Django 3.1.2 on 2020-11-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20201121_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='length',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.sessiontypes'),
        ),
    ]
